### ISSUE TITLE
User/admin sees members page (design done enough to start)

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget-ui#125]
Forgot about this. Necessary if we don't want to have to add groups' members by hand to the database.

**Comment by derekrazo** [comment]
@ahdinosaur - if you want to get this functionally going, I can style it up as per Jon's designs.

**Comment by derekrazo** [comment]
@jonlemmon - For an admin view, I'm thinking we also want to see email. We can just do this in the format of what you've got.

**Comment by ahdinosaur** [comment]
@derekrazo sweet as, thanks for posting the design link here.

@jonlemmon awesome design! question: do we really want to display "Member since"? it's very unlikely that Cobudget will be the source of truth of any group's membership information, which means it's likely the "Member since" info will be wrong, e.g. the Enspiral Services members page saying JV has been a member for 3 months. i'm curious of your thoughts that lead you to adding this, also my concerns would no be longer valid once we do have an app focused on being the source of truth for groups' membership information, which is the intent of [craftodex ("directory app")](https://github.com/craftodex).
